paths:
  historical_data: "btc_historical.csv"
  historical_data_clean: "btc_historical_clean.csv"
  dataset: "btc_dataset.csv"
  live_candles: "btc_live_candles.csv"
  models_dir: "models"
  logs_dir: "logs"

params:
  symbol: "BTCUSDT"
  interval: "1m"
  retrain_interval_minutes: 60
  dashboard_port: 8501
  fresh_start: True
